/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class im_years_mp3recorder_Lame */

#ifndef _Included_im_years_mp3recorder_Lame
#define _Included_im_years_mp3recorder_Lame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     im_years_mp3recorder_Lame
 * Method:    log
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_im_years_mp3recorder_Lame_log
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
