/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class im_years_mp3recorder_Encoder_Builder */

#ifndef _Included_im_years_mp3recorder_Encoder_Builder
#define _Included_im_years_mp3recorder_Encoder_Builder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
